chart: core-provider remove inconsistent pre-delete hook
In #454 the pre-delete hook was removed from the Namespace and in #508
it was removed from the CAPIProvider

However the pre-delete hook remains on the ConfigMap, which means if
installation fails for any reason prior to creating the Namespace in
the post-install hook, the chart can become undeletable with an error
like:

+ helm_v3 uninstall rancher-turtles --namespace rancher-turtles-system --wait
Error: warning: Hook pre-delete rancher-turtles/templates/core-provider.yaml failed: 1 error occurred:
	* namespaces "capi-system" not found